# from pydantic import BaseModel

# class CreateAttendance(BaseModel):
#     professional_id: str
#     health_unit_id: str
#     admin_id: str
#     model_used: str
#     model_result: str
#     expected_result: str
#     correct_diagnosis: bool
#     image_base64: str
#     observation: str
# api/src/interfaces/create_attendance.py
from pydantic import BaseModel, Field
from typing import Optional, List, Dict # Adicionar List, Dict, Optional

class BoundingBox(BaseModel):
    """Represents a bounding box with its coordinates and optional confidence/observations."""
    x: float = Field(..., description="X coordinate of the top-left corner")
    y: float = Field(..., description="Y coordinate of the top-left corner")
    width: float = Field(..., description="Width of the bounding box")
    height: float = Field(..., description="Height of the bounding box")
    confidence: Optional[float] = Field(None, description="Confidence score of the detection")
    observations: Optional[str] = Field(None, description="Observations related to the bounding box")


class CreateAttendance(BaseModel):
    health_unit_id: str = Field(..., description="ID of the health unit where the attendance occurred")
    model_used: str = Field(..., description="Identifier of the AI model used (e.g., 'respiratory', 'breast')")
    model_result: str = Field(..., description="Raw result/prediction generated by the AI model")
    expected_result: str = Field(..., description="The result expected or confirmed by the professional")
    correct_diagnosis: bool = Field(..., description="Whether the AI model's result matched the expected result")
    image_base64: str = Field(..., description="Base64 encoded image associated with the attendance")
    observation: Optional[str] = Field(None, description="General observations by the professional") # Tornar opcional
    bounding_boxes: Optional[List[BoundingBox]] = Field(None, description="List of bounding boxes, applicable for models like 'breast'") # Adicionado

    class Config:
        json_schema_extra = {
            "example": {
                "health_unit_id": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
                "model_used": "breast",
                "model_result": "Nodule detected",
                "expected_result": "Nodule detected",
                "correct_diagnosis": True,
                "image_base64": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA...",
                "observation": "Patient reported symptoms X and Y.",
                "bounding_boxes": [
                    {"x": 10.5, "y": 20.0, "width": 5.0, "height": 5.0, "confidence": 0.95, "observations": "Suspicious area"}
                ]
            }
        }